# This GitHub Action is intended to simply test that the
# Microservice Social-Cards is able to build with Docker properly.
name: Microservice Social-Cards Docker Build

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'microservices/social-cards/**'
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the latest code
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build .
